CREATE TABLE posts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    message TEXT,
    comment SMALLINT NOT NULL
);

CREATE TABLE likes (
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE comments (
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    comment_post_id BIGINT NOT NULL
);

CREATE TABLE reposts (
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE posts_photos (
    post_id BIGINT NOT NULL,
    photo_id BIGINT NOT NULL
);

CREATE TABLE posts_videos (
    post_id BIGINT NOT NULL,
    video_id BIGINT NOT NULL
);

CREATE TABLE posts_audios (
    post_id BIGINT NOT NULL,
    audio_id BIGINT NOT NULL
);

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username TEXT NOT NULL UNIQUE,
    realname TEXT NOT NULL,
    hashed_password TEXT NOT NULL,
    profile_picture_photo_id BIGINT,
    banner_photo_id BIGINT,
    bio TEXT
);

CREATE TABLE follows (
    user_id BIGINT NOT NULL,
    sub_user_id BIGINT NOT NULL
);

CREATE TABLE photos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    processing SMALLINT NOT NULL,
    profile_picture SMALLINT NOT NULL,
    banner SMALLINT NOT NULL,
    jpg_small BYTEA,
    jpg_medium BYTEA,
    jpg_large BYTEA,
    jpg_orig BYTEA
);

CREATE TABLE videos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    processing SMALLINT NOT NULL,
    mp4_480p BYTEA,
    mp4_720p BYTEA
);

CREATE TABLE audios (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    processing SMALLINT NOT NULL,
    mp3_128k BYTEA,
    mp3_320k BYTEA
);
