import sys

with open(sys.argv[1], "r") as f:
    with open(sys.argv[1].replace(".sql", "-postgres.sql"), "w") as fo:
        fo.write(
            f.read()
                .replace("INTEGER", "BIGINT")
                .replace("AUTOINCREMENT", "GENERATED BY DEFAULT AS IDENTITY")
                .replace("BLOB", "BYTEA")
                .replace("BIT", "SMALLINT")
        )